const express=require('express');const db=require('../db');const adminAuth=require('../middleware/adminAuth');const router=express.Router();
const slugify=value=>String(value||'gallery').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100)||`gallery-${Date.now()}`;
async function withItems(album){if(!album)return null;return{...album,items:await db.prepare('SELECT * FROM gallery_items WHERE album_id=? ORDER BY sort_order,id').all(album.id)}}
router.get('/public',async(_req,res)=>{const rows=await db.prepare('SELECT * FROM gallery_albums WHERE is_published=1 ORDER BY is_featured DESC,sort_order,id DESC').all();res.json(await Promise.all(rows.map(withItems)))});
router.get('/admin',adminAuth,async(_req,res)=>{const rows=await db.prepare('SELECT * FROM gallery_albums ORDER BY sort_order,id DESC').all();res.json(await Promise.all(rows.map(withItems)))});
router.post('/admin',adminAuth,async(req,res)=>{const title=String(req.body.title||'').trim();if(!title)return res.status(400).json({error:'Album title is required.'});let slug=slugify(req.body.slug||title),n=2;while(await db.prepare('SELECT id FROM gallery_albums WHERE slug=?').get(slug))slug=`${slugify(title)}-${n++}`;const out=await db.prepare('INSERT INTO gallery_albums(title,slug,description,is_published,is_featured,sort_order) VALUES(?,?,?,?,?,?)').run(title,slug,String(req.body.description||'').trim(),req.body.is_published?1:0,req.body.is_featured?1:0,Number(req.body.sort_order)||0);res.status(201).json(await withItems(await db.prepare('SELECT * FROM gallery_albums WHERE id=?').get(out.lastInsertRowid)))});
router.patch('/admin/:id',adminAuth,async(req,res)=>{const row=await db.prepare('SELECT * FROM gallery_albums WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({error:'Gallery album not found.'});const title=String(req.body.title??row.title).trim();await db.prepare('UPDATE gallery_albums SET title=?,description=?,is_published=?,is_featured=?,sort_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(title,String((req.body.description??row.description)||'').trim(),req.body.is_published===undefined?row.is_published:(req.body.is_published?1:0),req.body.is_featured===undefined?row.is_featured:(req.body.is_featured?1:0),Number(req.body.sort_order??row.sort_order)||0,row.id);res.json(await withItems(await db.prepare('SELECT * FROM gallery_albums WHERE id=?').get(row.id)))});
router.delete('/admin/:id',adminAuth,async(req,res)=>{const row=await db.prepare('SELECT id FROM gallery_albums WHERE id=?').get(req.params.id);if(!row)return res.status(404).json({error:'Gallery album not found.'});await db.prepare('DELETE FROM gallery_albums WHERE id=?').run(row.id);res.json({deleted:true})});
router.post('/admin/:id/items',adminAuth,async(req,res)=>{const album=await db.prepare('SELECT * FROM gallery_albums WHERE id=?').get(req.params.id);if(!album)return res.status(404).json({error:'Gallery album not found.'});const items=Array.isArray(req.body.items)?req.body.items:[];if(!items.length)return res.status(400).json({error:'Select at least one media item.'});const insert=db.prepare('INSERT INTO gallery_items(album_id,media_type,media_url,thumbnail_url,source_type,source_id,caption,sort_order) VALUES(?,?,?,?,?,?,?,?)');for(let i=0;i<items.length;i+=1){const item=items[i];await insert.run(album.id,item.media_type,item.media_url,item.thumbnail_url||'',item.source_type||'',String(item.source_id||''),item.caption||item.display_name||'',Number(item.sort_order)||i)}const first=await db.prepare('SELECT media_url,thumbnail_url FROM gallery_items WHERE album_id=? ORDER BY sort_order,id LIMIT 1').get(album.id);if(first&&!album.cover_url)await db.prepare('UPDATE gallery_albums SET cover_url=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(first.thumbnail_url||first.media_url,album.id);res.status(201).json(await withItems(await db.prepare('SELECT * FROM gallery_albums WHERE id=?').get(album.id)))});
router.patch('/admin/:albumId/items/:itemId',adminAuth,async(req,res)=>{const row=await db.prepare('SELECT * FROM gallery_items WHERE id=? AND album_id=?').get(req.params.itemId,req.params.albumId);if(!row)return res.status(404).json({error:'Gallery item not found.'});await db.prepare('UPDATE gallery_items SET caption=?,sort_order=? WHERE id=?').run(String((req.body.caption??row.caption)||''),Number(req.body.sort_order??row.sort_order)||0,row.id);res.json(await db.prepare('SELECT * FROM gallery_items WHERE id=?').get(row.id))});
router.delete('/admin/:albumId/items/:itemId',adminAuth,async(req,res)=>{const row=await db.prepare('SELECT * FROM gallery_items WHERE id=? AND album_id=?').get(req.params.itemId,req.params.albumId);if(!row)return res.status(404).json({error:'Gallery item not found.'});await db.prepare('DELETE FROM gallery_items WHERE id=?').run(row.id);res.json({removed:true})});
module.exports=router;
